CREATE TABLE NUMBERPLATES
(
    ID          INT PRIMARY KEY AUTO_INCREMENT,
    IMAGE 		LONGTEXT,
    FILENAME    VARCHAR(255),
    CONTENTTYPE VARCHAR(255),
    OWNER		VARCHAR(32),
    DETAILS		LONGTEXT,
    NUMBER		VARCHAR(255),
    CREATED     TIMESTAMP DEFAULT NOW()
);
CREATE TABLE USERS
(
    ID          INT PRIMARY KEY AUTO_INCREMENT,
    USERNAME	VARCHAR(32),
    PASSWORD    VARCHAR(32),
    ENABLED		VARCHAR(32),
    CREATED     TIMESTAMP DEFAULT NOW(),
    UNIQUE (USERNAME)    
);
CREATE TABLE PERSISTENTLOGINS
(
    ID          INT PRIMARY KEY AUTO_INCREMENT,
    USERNAME	VARCHAR(32),
    SERIES		VARCHAR(32),
    TOKEN		VARCHAR(32),
    LASTUSED	VARCHAR(32)
);